name: chat_firebase_dio
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-66.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  uuid: ^3.0.6
  flutter_lints: ^2.0.0
  firebase_core: ^1.24.0
  cloud_firestore: ^3.5.1
  firebase_analytics: ^9.3.8
  firebase_messaging: ^13.1.0
  firebase_crashlytics: ^2.9.0
  firebase_remote_config: ^2.0.20

flutter:

  
  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
